### ISSUE TITLE
Coinbase wallet popup appears when the user tries to connect to other wallets (not in our current version but in some new branches)

### ISSUE THREAD

**Issue by kingalg** [levelkdev/swapr-dapp#624] opened 2022-02-09 12:46 UTC
Coinbase wallet popup appears when the user tries to connect to other wallets. You can observe this in some of the new branches. For example in the branch that you need to connect to when testing [https://github.com/levelkdev/dxswap-dapp/pull/616](url) 

What is happening: this popup appears when I'm trying to connect to Metamask (note: once the popup is closed connection to Metamask happens as usual):
![Screenshot 2022-02-09 at 13.38.39.png](https://images.zenhubusercontent.com/61b8ae8c4021b5ba7f93dbf2/74d7bfb3-32ed-4993-b9ff-45c5eff835d2)

**Comment by karczuRF** [comment] 2022-02-21 11:53
The problem is not on our side and comes from Coinbase Wallet itself, details here: https://github.com/NoahZinsmeister/web3-react/issues/300
Solution can come with library update or can be implemented as explained in that comment: https://github.com/NoahZinsmeister/web3-react/issues/300#issuecomment-995170556

**Comment by MilanVojnovic95** [comment] 2022-08-26 12:09
This bug is fixed in #1330

**Closed** 2022-08-26 13:36 UTC
Labels: bug
